-- AUTO-GENERATED FILE.

-- This file is an auto-generated file by Ballerina persistence layer for model.
-- Please verify the generated scripts and execute them against the target DB server.

DROP TABLE IF EXISTS "TestScriptTable";
DROP TABLE IF EXISTS "TestReportTable";
DROP TABLE IF EXISTS "RelatedPersonTable";
DROP TABLE IF EXISTS "EvidenceVariableTable";
DROP TABLE IF EXISTS "ValueSetTable";
DROP TABLE IF EXISTS "DocumentManifestTable";
DROP TABLE IF EXISTS "ImmunizationRecommendationTable";
DROP TABLE IF EXISTS "DeviceMetricTable";
DROP TABLE IF EXISTS "REFERENCE_TABLE";
DROP TABLE IF EXISTS "LocationTable";
DROP TABLE IF EXISTS "ExplanationOfBenefitTable";
DROP TABLE IF EXISTS "FlagTable";
DROP TABLE IF EXISTS "MedicationStatementTable";
DROP TABLE IF EXISTS "InsurancePlanTable";
DROP TABLE IF EXISTS "MedicinalProductContraindicationTable";
DROP TABLE IF EXISTS "ClaimResponseTable";
DROP TABLE IF EXISTS "MedicinalProductAuthorizationTable";
DROP TABLE IF EXISTS "ImagingStudyTable";
DROP TABLE IF EXISTS "PractitionerRoleTable";
DROP TABLE IF EXISTS "GroupTable";
DROP TABLE IF EXISTS "PersonTable";
DROP TABLE IF EXISTS "PractitionerTable";
DROP TABLE IF EXISTS "ActivityDefinitionTable";
DROP TABLE IF EXISTS "EvidenceTable";
DROP TABLE IF EXISTS "DeviceTable";
DROP TABLE IF EXISTS "FamilyMemberHistoryTable";
DROP TABLE IF EXISTS "AdverseEventTable";
DROP TABLE IF EXISTS "SupplyRequestTable";
DROP TABLE IF EXISTS "ExampleScenarioTable";
DROP TABLE IF EXISTS "InvoiceTable";
DROP TABLE IF EXISTS "QuestionnaireResponseTable";
DROP TABLE IF EXISTS "ObservationTable";
DROP TABLE IF EXISTS "EffectEvidenceSynthesisTable";
DROP TABLE IF EXISTS "OperationDefinitionTable";
DROP TABLE IF EXISTS "MeasureReportTable";
DROP TABLE IF EXISTS "SupplyDeliveryTable";
DROP TABLE IF EXISTS "ServiceRequestTable";
DROP TABLE IF EXISTS "BasicTable";
DROP TABLE IF EXISTS "SubscriptionTable";
DROP TABLE IF EXISTS "EnrollmentResponseTable";
DROP TABLE IF EXISTS "DeviceRequestTable";
DROP TABLE IF EXISTS "AppointmentTable";
DROP TABLE IF EXISTS "NamingSystemTable";
DROP TABLE IF EXISTS "StructureDefinitionTable";
DROP TABLE IF EXISTS "ClinicalImpressionTable";
DROP TABLE IF EXISTS "CommunicationTable";
DROP TABLE IF EXISTS "OrganizationTable";
DROP TABLE IF EXISTS "CoverageEligibilityResponseTable";
DROP TABLE IF EXISTS "ResearchStudyTable";
DROP TABLE IF EXISTS "BundleTable";
DROP TABLE IF EXISTS "EncounterTable";
DROP TABLE IF EXISTS "RiskAssessmentTable";
DROP TABLE IF EXISTS "ListTable";
DROP TABLE IF EXISTS "OrganizationAffiliationTable";
DROP TABLE IF EXISTS "ChargeItemTable";
DROP TABLE IF EXISTS "MedicationKnowledgeTable";
DROP TABLE IF EXISTS "PlanDefinitionTable";
DROP TABLE IF EXISTS "CarePlanTable";
DROP TABLE IF EXISTS "VisionPrescriptionTable";
DROP TABLE IF EXISTS "EpisodeOfCareTable";
DROP TABLE IF EXISTS "CareTeamTable";
DROP TABLE IF EXISTS "MedicationAdministrationTable";
DROP TABLE IF EXISTS "ConsentTable";
DROP TABLE IF EXISTS "DetectedIssueTable";
DROP TABLE IF EXISTS "SubstanceSpecificationTable";
DROP TABLE IF EXISTS "AllergyIntoleranceTable";
DROP TABLE IF EXISTS "MedicinalProductIndicationTable";
DROP TABLE IF EXISTS "MedicinalProductPharmaceuticalTable";
DROP TABLE IF EXISTS "SlotTable";
DROP TABLE IF EXISTS "VerificationResultTable";
DROP TABLE IF EXISTS "SpecimenTable";
DROP TABLE IF EXISTS "ResearchSubjectTable";
DROP TABLE IF EXISTS "MedicationTable";
DROP TABLE IF EXISTS "ResearchDefinitionTable";
DROP TABLE IF EXISTS "HealthcareServiceTable";
DROP TABLE IF EXISTS "PaymentNoticeTable";
DROP TABLE IF EXISTS "ProvenanceTable";
DROP TABLE IF EXISTS "GraphDefinitionTable";
DROP TABLE IF EXISTS "MediaTable";
DROP TABLE IF EXISTS "BodyStructureTable";
DROP TABLE IF EXISTS "DiagnosticReportTable";
DROP TABLE IF EXISTS "GoalTable";
DROP TABLE IF EXISTS "CapabilityStatementTable";
DROP TABLE IF EXISTS "DeviceUseStatementTable";
DROP TABLE IF EXISTS "ScheduleTable";
DROP TABLE IF EXISTS "MedicinalProductPackagedTable";
DROP TABLE IF EXISTS "ProcedureTable";
DROP TABLE IF EXISTS "LibraryTable";
DROP TABLE IF EXISTS "CodeSystemTable";
DROP TABLE IF EXISTS "CommunicationRequestTable";
DROP TABLE IF EXISTS "DocumentReferenceTable";
DROP TABLE IF EXISTS "RequestGroupTable";
DROP TABLE IF EXISTS "ClaimTable";
DROP TABLE IF EXISTS "MessageDefinitionTable";
DROP TABLE IF EXISTS "RiskEvidenceSynthesisTable";
DROP TABLE IF EXISTS "TaskTable";
DROP TABLE IF EXISTS "ImplementationGuideTable";
DROP TABLE IF EXISTS "StructureMapTable";
DROP TABLE IF EXISTS "MedicinalProductUndesirableEffectTable";
DROP TABLE IF EXISTS "CompartmentDefinitionTable";
DROP TABLE IF EXISTS "EndpointTable";
DROP TABLE IF EXISTS "TerminologyCapabilitiesTable";
DROP TABLE IF EXISTS "ConditionTable";
DROP TABLE IF EXISTS "CompositionTable";
DROP TABLE IF EXISTS "ContractTable";
DROP TABLE IF EXISTS "ImmunizationTable";
DROP TABLE IF EXISTS "MedicationDispenseTable";
DROP TABLE IF EXISTS "MolecularSequenceTable";
DROP TABLE IF EXISTS "SearchParameterTable";
DROP TABLE IF EXISTS "MedicationRequestTable";
DROP TABLE IF EXISTS "EnrollmentRequestTable";
DROP TABLE IF EXISTS "SpecimenDefinitionTable";
DROP TABLE IF EXISTS "EventDefinitionTable";
DROP TABLE IF EXISTS "ImmunizationEvaluationTable";
DROP TABLE IF EXISTS "PaymentReconciliationTable";
DROP TABLE IF EXISTS "MeasureTable";
DROP TABLE IF EXISTS "ConceptMapTable";
DROP TABLE IF EXISTS "ResearchElementDefinitionTable";
DROP TABLE IF EXISTS "GuidanceResponseTable";
DROP TABLE IF EXISTS "LinkageTable";
DROP TABLE IF EXISTS "MedicinalProductTable";
DROP TABLE IF EXISTS "DeviceDefinitionTable";
DROP TABLE IF EXISTS "CoverageEligibilityRequestTable";
DROP TABLE IF EXISTS "PatientTable";
DROP TABLE IF EXISTS "CoverageTable";
DROP TABLE IF EXISTS "SubstanceTable";
DROP TABLE IF EXISTS "ChargeItemDefinitionTable";
DROP TABLE IF EXISTS "SEARCH_PARAM_RES_EXPRESSION_TABLE";
DROP TABLE IF EXISTS "MedicinalProductInteractionTable";
DROP TABLE IF EXISTS "AccountTable";
DROP TABLE IF EXISTS "MessageHeaderTable";
DROP TABLE IF EXISTS "AuditEventTable";
DROP TABLE IF EXISTS "NutritionOrderTable";
DROP TABLE IF EXISTS "QuestionnaireTable";
DROP TABLE IF EXISTS "AppointmentResponseTable";

CREATE TABLE "AppointmentResponseTable" (
	"ID" INT AUTO_INCREMENT,
	"PART_STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "QuestionnaireTable" (
	"ID" INT AUTO_INCREMENT,
	"DEFINITION" VARCHAR(512),
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"SUBJECT_TYPE" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "NutritionOrderTable" (
	"ID" INT AUTO_INCREMENT,
	"SUPPLEMENT" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DATETIME" DATE,
	"INSTANTIATES_URI" VARCHAR(512),
	"ADDITIVE" VARCHAR(2048),
	"ORALDIET" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"FORMULA" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "AuditEventTable" (
	"ID" INT AUTO_INCREMENT,
	"SUBTYPE" VARCHAR(2048),
	"SITE" VARCHAR(2048),
	"OUTCOME" VARCHAR(2048),
	"ENTITY_ROLE" VARCHAR(2048),
	"AGENT_NAME" VARCHAR(512),
	"ENTITY_TYPE" VARCHAR(2048),
	"DATE" DATE,
	"POLICY" VARCHAR(512),
	"ALTID" VARCHAR(2048),
	"ACTION" VARCHAR(2048),
	"ADDRESS" VARCHAR(512),
	"TYPE" VARCHAR(2048),
	"ENTITY_NAME" VARCHAR(512),
	"AGENT_ROLE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MessageHeaderTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"SOURCE_URI" VARCHAR(512),
	"DESTINATION" VARCHAR(512),
	"DESTINATION_URI" VARCHAR(512),
	"SOURCE" VARCHAR(512),
	"RESPONSE_ID" VARCHAR(2048),
	"EVENT" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "AccountTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"PERIOD" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductInteractionTable" (
	"ID" INT AUTO_INCREMENT,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SEARCH_PARAM_RES_EXPRESSION_TABLE" (
	"ID" INT AUTO_INCREMENT,
	"SEARCH_PARAM_NAME" VARCHAR(191) NOT NULL,
	"SEARCH_PARAM_TYPE" VARCHAR(191) NOT NULL,
	"RESOURCE_NAME" VARCHAR(191) NOT NULL,
	"EXPRESSION" VARCHAR(191) NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ChargeItemDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SubstanceTable" (
	"ID" INT AUTO_INCREMENT,
	"CONTAINER_IDENTIFIER" VARCHAR(2048),
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"QUANTITY" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"EXPIRY" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CoverageTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"DEPENDENT" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CLASS_VALUE" VARCHAR(512),
	"TYPE" VARCHAR(2048),
	"CLASS_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PatientTable" (
	"ID" INT AUTO_INCREMENT,
	"LANGUAGE" VARCHAR(2048),
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"ACTIVE" VARCHAR(2048),
	"PHONE" VARCHAR(2048),
	"DECEASED" VARCHAR(2048),
	"BIRTHDATE" DATE,
	"ADDRESS_CITY" VARCHAR(512),
	"EMAIL" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"TELECOM" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"FAMILY" VARCHAR(512),
	"ADDRESS_USE" VARCHAR(2048),
	"GIVEN" VARCHAR(512),
	"ADDRESS" VARCHAR(512),
	"GENDER" VARCHAR(2048),
	"PHONETIC" VARCHAR(512),
	"DEATH_DATE" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CoverageEligibilityRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DeviceDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductTable" (
	"ID" INT AUTO_INCREMENT,
	"NAME_LANGUAGE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "LinkageTable" (
	"ID" INT AUTO_INCREMENT,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "GuidanceResponseTable" (
	"ID" INT AUTO_INCREMENT,
	"REQUEST" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ResearchElementDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ConceptMapTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"SOURCE_SYSTEM" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"TARGET_SYSTEM" VARCHAR(512),
	"SOURCE_CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"TARGET_CODE" VARCHAR(2048),
	"PRODUCT" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"DEPENDSON" VARCHAR(512),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MeasureTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PaymentReconciliationTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"OUTCOME" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"DISPOSITION" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ImmunizationEvaluationTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"TARGET_DISEASE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"DOSE_STATUS" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EventDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SpecimenDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"CONTAINER" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EnrollmentRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicationRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"INTENT" VARCHAR(2048),
	"PRIORITY" VARCHAR(2048),
	"INTENDED_PERFORMERTYPE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"AUTHOREDON" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SearchParameterTable" (
	"ID" INT AUTO_INCREMENT,
	"TARGET" VARCHAR(2048),
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"BASE" VARCHAR(2048),
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MolecularSequenceTable" (
	"ID" INT AUTO_INCREMENT,
	"CHROMOSOME" VARCHAR(2048),
	"VARIANT_START" INT,
	"WINDOW_START" INT,
	"VARIANT_END" INT,
	"REFERENCESEQID" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"WINDOW_END" INT,
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicationDispenseTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"WHENHANDEDOVER" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"WHENPREPARED" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ImmunizationTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"VACCINE_CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"STATUS_REASON" VARCHAR(2048),
	"SERIES" VARCHAR(512),
	"TARGET_DISEASE" VARCHAR(2048),
	"REASON_CODE" VARCHAR(2048),
	"REACTION_DATE" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"LOT_NUMBER" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ContractTable" (
	"ID" INT AUTO_INCREMENT,
	"ISSUED" DATE,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"INSTANTIATES" VARCHAR(512),
	"URL" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CompositionTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"RELATED_ID" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"PERIOD" DATE,
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"CONFIDENTIALITY" VARCHAR(2048),
	"SECTION" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ConditionTable" (
	"ID" INT AUTO_INCREMENT,
	"CLINICAL_STATUS" VARCHAR(2048),
	"STAGE" VARCHAR(2048),
	"ONSET_AGE" VARCHAR(2048),
	"ONSET_INFO" VARCHAR(512),
	"EVIDENCE" VARCHAR(2048),
	"ONSET_DATE" DATE,
	"BODY_SITE" VARCHAR(2048),
	"VERIFICATION_STATUS" VARCHAR(2048),
	"CODE" VARCHAR(2048),
	"ABATEMENT_AGE" VARCHAR(2048),
	"ABATEMENT_STRING" VARCHAR(512),
	"RECORDED_DATE" DATE,
	"CATEGORY" VARCHAR(2048),
	"ABATEMENT_DATE" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"SEVERITY" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "TerminologyCapabilitiesTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"PUBLISHER" VARCHAR(512),
	"STATUS" VARCHAR(2048),
	"JURISDICTION" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"CONTEXT_TYPE" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EndpointTable" (
	"ID" INT AUTO_INCREMENT,
	"CONNECTION_TYPE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"PAYLOAD_TYPE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CompartmentDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"PUBLISHER" VARCHAR(512),
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"RESOURCE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductUndesirableEffectTable" (
	"ID" INT AUTO_INCREMENT,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "StructureMapTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ImplementationGuideTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EXPERIMENTAL" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "TaskTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"BUSINESS_STATUS" VARCHAR(2048),
	"PERIOD" DATE,
	"AUTHORED_ON" DATE,
	"INTENT" VARCHAR(2048),
	"PRIORITY" VARCHAR(2048),
	"GROUP_IDENTIFIER" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"PERFORMER" VARCHAR(2048),
	"MODIFIED" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "RiskEvidenceSynthesisTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MessageDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"FOCUS" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"EVENT" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"CATEGORY" VARCHAR(2048),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ClaimTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"USE" VARCHAR(2048),
	"PRIORITY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "RequestGroupTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"INSTANTIATES_URI" VARCHAR(512),
	"INTENT" VARCHAR(2048),
	"AUTHORED" DATE,
	"PRIORITY" VARCHAR(2048),
	"GROUP_IDENTIFIER" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DocumentReferenceTable" (
	"ID" INT AUTO_INCREMENT,
	"LANGUAGE" VARCHAR(2048),
	"LOCATION" VARCHAR(512),
	"CONTENTTYPE" VARCHAR(2048),
	"RELATION" VARCHAR(2048),
	"FORMAT" VARCHAR(2048),
	"FACILITY" VARCHAR(2048),
	"EVENT" VARCHAR(2048),
	"DATE" DATE,
	"SECURITY_LABEL" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"CATEGORY" VARCHAR(2048),
	"PERIOD" DATE,
	"SETTING" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CommunicationRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"MEDIUM" VARCHAR(2048),
	"OCCURRENCE" DATE,
	"CATEGORY" VARCHAR(2048),
	"AUTHORED" DATE,
	"PRIORITY" VARCHAR(2048),
	"GROUP_IDENTIFIER" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CodeSystemTable" (
	"ID" INT AUTO_INCREMENT,
	"LANGUAGE" VARCHAR(2048),
	"SYSTEM" VARCHAR(512),
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"CONTENT_MODE" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "LibraryTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"CONTENT_TYPE" VARCHAR(2048),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ProcedureTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"INSTANTIATES_URI" VARCHAR(512),
	"CATEGORY" VARCHAR(2048),
	"REASON_CODE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductPackagedTable" (
	"ID" INT AUTO_INCREMENT,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ScheduleTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"SERVICE_CATEGORY" VARCHAR(2048),
	"ACTIVE" VARCHAR(2048),
	"SPECIALTY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"SERVICE_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DeviceUseStatementTable" (
	"ID" INT AUTO_INCREMENT,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CapabilityStatementTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"FORMAT" VARCHAR(2048),
	"MODE" VARCHAR(2048),
	"SECURITY_SERVICE" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"SOFTWARE" VARCHAR(512),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"FHIRVERSION" VARCHAR(2048),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"RESOURCE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "GoalTable" (
	"ID" INT AUTO_INCREMENT,
	"TARGET_DATE" DATE,
	"ACHIEVEMENT_STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"LIFECYCLE_STATUS" VARCHAR(2048),
	"START_DATE" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DiagnosticReportTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"ISSUED" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"CONCLUSION" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "BodyStructureTable" (
	"ID" INT AUTO_INCREMENT,
	"LOCATION" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"MORPHOLOGY" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MediaTable" (
	"ID" INT AUTO_INCREMENT,
	"SITE" VARCHAR(2048),
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"MODALITY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VIEW" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "GraphDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"PUBLISHER" VARCHAR(512),
	"STATUS" VARCHAR(2048),
	"JURISDICTION" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"START" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"CONTEXT_TYPE" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ProvenanceTable" (
	"ID" INT AUTO_INCREMENT,
	"RECORDED" DATE,
	"WHEN" DATE,
	"AGENT_TYPE" VARCHAR(2048),
	"SIGNATURE_TYPE" VARCHAR(2048),
	"AGENT_ROLE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PaymentNoticeTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"PAYMENT_STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "HealthcareServiceTable" (
	"ID" INT AUTO_INCREMENT,
	"SERVICE_CATEGORY" VARCHAR(2048),
	"CHARACTERISTIC" VARCHAR(2048),
	"ACTIVE" VARCHAR(2048),
	"SPECIALTY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"SERVICE_TYPE" VARCHAR(2048),
	"PROGRAM" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ResearchDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicationTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"EXPIRATION_DATE" DATE,
	"FORM" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"LOT_NUMBER" VARCHAR(2048),
	"INGREDIENT_CODE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ResearchSubjectTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SpecimenTable" (
	"ID" INT AUTO_INCREMENT,
	"COLLECTED" DATE,
	"STATUS" VARCHAR(2048),
	"ACCESSION" VARCHAR(2048),
	"CONTAINER" VARCHAR(2048),
	"BODYSITE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTAINER_ID" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "VerificationResultTable" (
	"ID" INT AUTO_INCREMENT,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SlotTable" (
	"ID" INT AUTO_INCREMENT,
	"SERVICE_CATEGORY" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"APPOINTMENT_TYPE" VARCHAR(2048),
	"SPECIALTY" VARCHAR(2048),
	"START" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"SERVICE_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductPharmaceuticalTable" (
	"ID" INT AUTO_INCREMENT,
	"ROUTE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TARGET_SPECIES" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductIndicationTable" (
	"ID" INT AUTO_INCREMENT,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "AllergyIntoleranceTable" (
	"ID" INT AUTO_INCREMENT,
	"ROUTE" VARCHAR(2048),
	"LAST_DATE" DATE,
	"MANIFESTATION" VARCHAR(2048),
	"CLINICAL_STATUS" VARCHAR(2048),
	"VERIFICATION_STATUS" VARCHAR(2048),
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"CRITICALITY" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"SEVERITY" VARCHAR(2048),
	"ONSET" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SubstanceSpecificationTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DetectedIssueTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"IDENTIFIED" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ConsentTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"SECURITY_LABEL" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"ACTION" VARCHAR(2048),
	"SCOPE" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"PERIOD" DATE,
	"PURPOSE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicationAdministrationTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"REASON_NOT_GIVEN" VARCHAR(2048),
	"EFFECTIVE_TIME" DATE,
	"REASON_GIVEN" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CareTeamTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EpisodeOfCareTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "VisionPrescriptionTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"DATEWRITTEN" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CarePlanTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"INSTANTIATES_URI" VARCHAR(512),
	"CATEGORY" VARCHAR(2048),
	"INTENT" VARCHAR(2048),
	"ACTIVITY_DATE" DATE,
	"ACTIVITY_CODE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PlanDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicationKnowledgeTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"SOURCE_COST" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"MONITORING_PROGRAM_NAME" VARCHAR(2048),
	"CLASSIFICATION_TYPE" VARCHAR(2048),
	"CLASSIFICATION" VARCHAR(2048),
	"DOSEFORM" VARCHAR(2048),
	"MONOGRAPH_TYPE" VARCHAR(2048),
	"MONITORING_PROGRAM_TYPE" VARCHAR(2048),
	"INGREDIENT_CODE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ChargeItemTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"FACTOR_OVERRIDE" INT,
	"QUANTITY" VARCHAR(2048),
	"OCCURRENCE" DATE,
	"PRICE_OVERRIDE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"ENTERED_DATE" DATE,
	"PERFORMER_FUNCTION" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "OrganizationAffiliationTable" (
	"ID" INT AUTO_INCREMENT,
	"ROLE" VARCHAR(2048),
	"DATE" DATE,
	"ACTIVE" VARCHAR(2048),
	"PHONE" VARCHAR(2048),
	"SPECIALTY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"EMAIL" VARCHAR(2048),
	"TELECOM" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ListTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"NOTES" VARCHAR(512),
	"EMPTY_REASON" VARCHAR(2048),
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "RiskAssessmentTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"PROBABILITY" INT,
	"METHOD" VARCHAR(2048),
	"RISK" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EncounterTable" (
	"ID" INT AUTO_INCREMENT,
	"PARTICIPANT_TYPE" VARCHAR(2048),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"LENGTH" VARCHAR(2048),
	"REASON_CODE" VARCHAR(2048),
	"SPECIAL_ARRANGEMENT" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"CLASS" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"LOCATION_PERIOD" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "BundleTable" (
	"ID" INT AUTO_INCREMENT,
	"TIMESTAMP" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ResearchStudyTable" (
	"ID" INT AUTO_INCREMENT,
	"LOCATION" VARCHAR(2048),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"FOCUS" VARCHAR(2048),
	"KEYWORD" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CoverageEligibilityResponseTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"OUTCOME" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"DISPOSITION" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "OrganizationTable" (
	"ID" INT AUTO_INCREMENT,
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"ADDRESS_USE" VARCHAR(2048),
	"ACTIVE" VARCHAR(2048),
	"ADDRESS" VARCHAR(512),
	"PHONETIC" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"ADDRESS_CITY" VARCHAR(512),
	"TYPE" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "CommunicationTable" (
	"ID" INT AUTO_INCREMENT,
	"RECEIVED" DATE,
	"STATUS" VARCHAR(2048),
	"MEDIUM" VARCHAR(2048),
	"INSTANTIATES_URI" VARCHAR(512),
	"CATEGORY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"SENT" DATE,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ClinicalImpressionTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"FINDING_CODE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "StructureDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PATH" VARCHAR(2048),
	"DERIVATION" VARCHAR(2048),
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"BASE_PATH" VARCHAR(2048),
	"EXPERIMENTAL" VARCHAR(2048),
	"KEYWORD" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"ABSTRACT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"KIND" VARCHAR(2048),
	"VERSION" VARCHAR(2048),
	"EXT_CONTEXT" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(512),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "NamingSystemTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"RESPONSIBLE" VARCHAR(512),
	"CONTACT" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"VALUE" VARCHAR(512),
	"ID_TYPE" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"TELECOM" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"PERIOD" DATE,
	"KIND" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "AppointmentTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"SERVICE_CATEGORY" VARCHAR(2048),
	"PART_STATUS" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"APPOINTMENT_TYPE" VARCHAR(2048),
	"REASON_CODE" VARCHAR(2048),
	"SPECIALTY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"SERVICE_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DeviceRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"EVENT_DATE" DATE,
	"STATUS" VARCHAR(2048),
	"INSTANTIATES_URI" VARCHAR(512),
	"AUTHORED_ON" DATE,
	"INTENT" VARCHAR(2048),
	"GROUP_IDENTIFIER" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EnrollmentResponseTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SubscriptionTable" (
	"ID" INT AUTO_INCREMENT,
	"CRITERIA" VARCHAR(512),
	"CONTACT" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"PAYLOAD" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"URL" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "BasicTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"CREATED" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ServiceRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"REQUISITION" VARCHAR(2048),
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"OCCURRENCE" DATE,
	"INSTANTIATES_URI" VARCHAR(512),
	"PERFORMER_TYPE" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"INTENT" VARCHAR(2048),
	"AUTHORED" DATE,
	"PRIORITY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"BODY_SITE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SupplyDeliveryTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MeasureReportTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"PERIOD" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "OperationDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"SYSTEM" VARCHAR(2048),
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"INSTANCE" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"KIND" VARCHAR(2048),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EffectEvidenceSynthesisTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ObservationTable" (
	"ID" INT AUTO_INCREMENT,
	"COMPONENT_CODE" VARCHAR(2048),
	"VALUE_QUANTITY" VARCHAR(2048),
	"COMBO_CODE" VARCHAR(2048),
	"VALUE_DATE" DATE,
	"DATE" DATE,
	"VALUE_STRING" VARCHAR(512),
	"COMBO_DATA_ABSENT_REASON" VARCHAR(2048),
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"COMBO_VALUE_QUANTITY" VARCHAR(2048),
	"VALUE_CONCEPT" VARCHAR(2048),
	"METHOD" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"COMPONENT_DATA_ABSENT_REASON" VARCHAR(2048),
	"DATA_ABSENT_REASON" VARCHAR(2048),
	"COMPONENT_VALUE_QUANTITY" VARCHAR(2048),
	"COMPONENT_VALUE_CONCEPT" VARCHAR(2048),
	"COMBO_VALUE_CONCEPT" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "QuestionnaireResponseTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"AUTHORED" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "InvoiceTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"TOTALNET" VARCHAR(2048),
	"PARTICIPANT_ROLE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"TOTALGROSS" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ExampleScenarioTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"PUBLISHER" VARCHAR(512),
	"STATUS" VARCHAR(2048),
	"JURISDICTION" VARCHAR(2048),
	"VERSION" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"CONTEXT_TYPE" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "SupplyRequestTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "AdverseEventTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"CATEGORY" VARCHAR(2048),
	"SERIOUSNESS" VARCHAR(2048),
	"ACTUALITY" VARCHAR(2048),
	"SEVERITY" VARCHAR(2048),
	"EVENT" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "FamilyMemberHistoryTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"INSTANTIATES_URI" VARCHAR(512),
	"SEX" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"RELATIONSHIP" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DeviceTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"UDI_DI" VARCHAR(512),
	"UDI_CARRIER" VARCHAR(512),
	"DEVICE_NAME" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"MODEL" VARCHAR(512),
	"MANUFACTURER" VARCHAR(512),
	"TYPE" VARCHAR(2048),
	"URL" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EvidenceTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ActivityDefinitionTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PractitionerTable" (
	"ID" INT AUTO_INCREMENT,
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"ACTIVE" VARCHAR(2048),
	"PHONE" VARCHAR(2048),
	"ADDRESS_CITY" VARCHAR(512),
	"EMAIL" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"TELECOM" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"FAMILY" VARCHAR(512),
	"ADDRESS_USE" VARCHAR(2048),
	"GIVEN" VARCHAR(512),
	"ADDRESS" VARCHAR(512),
	"GENDER" VARCHAR(2048),
	"PHONETIC" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"COMMUNICATION" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PersonTable" (
	"ID" INT AUTO_INCREMENT,
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"PHONE" VARCHAR(2048),
	"BIRTHDATE" DATE,
	"ADDRESS_CITY" VARCHAR(512),
	"EMAIL" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"TELECOM" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"ADDRESS_USE" VARCHAR(2048),
	"ADDRESS" VARCHAR(512),
	"GENDER" VARCHAR(2048),
	"PHONETIC" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "GroupTable" (
	"ID" INT AUTO_INCREMENT,
	"CHARACTERISTIC" VARCHAR(2048),
	"CODE" VARCHAR(2048),
	"EXCLUDE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VALUE" VARCHAR(2048),
	"ACTUAL" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "PractitionerRoleTable" (
	"ID" INT AUTO_INCREMENT,
	"ROLE" VARCHAR(2048),
	"DATE" DATE,
	"ACTIVE" VARCHAR(2048),
	"PHONE" VARCHAR(2048),
	"SPECIALTY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"EMAIL" VARCHAR(2048),
	"TELECOM" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ImagingStudyTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"DICOM_CLASS" VARCHAR(2048),
	"SERIES" VARCHAR(2048),
	"MODALITY" VARCHAR(2048),
	"STARTED" DATE,
	"BODYSITE" VARCHAR(2048),
	"INSTANCE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"REASON" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductAuthorizationTable" (
	"ID" INT AUTO_INCREMENT,
	"STATUS" VARCHAR(2048),
	"COUNTRY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ClaimResponseTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"OUTCOME" VARCHAR(2048),
	"USE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"PAYMENT_DATE" DATE,
	"DISPOSITION" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicinalProductContraindicationTable" (
	"ID" INT AUTO_INCREMENT,
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "InsurancePlanTable" (
	"ID" INT AUTO_INCREMENT,
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"STATUS" VARCHAR(2048),
	"ADDRESS_USE" VARCHAR(2048),
	"ADDRESS" VARCHAR(512),
	"PHONETIC" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"ADDRESS_CITY" VARCHAR(512),
	"TYPE" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "MedicationStatementTable" (
	"ID" INT AUTO_INCREMENT,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"CATEGORY" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "FlagTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ExplanationOfBenefitTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"DISPOSITION" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "LocationTable" (
	"ID" INT AUTO_INCREMENT,
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"STATUS" VARCHAR(2048),
	"ADDRESS_USE" VARCHAR(2048),
	"ADDRESS" VARCHAR(512),
	"OPERATIONAL_STATUS" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"ADDRESS_CITY" VARCHAR(512),
	"TYPE" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"NAME" VARCHAR(512),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "REFERENCE_TABLE" (
	"ID" INT AUTO_INCREMENT,
	"SOURCE_RESOURCE_TYPE" VARCHAR(191) NOT NULL,
	"SOURCE_RESOURCE_ID" VARCHAR(191) NOT NULL,
	"SOURCE_EXPRESSION" VARCHAR(191) NOT NULL,
	"TARGET_RESOURCE_TYPE" VARCHAR(191) NOT NULL,
	"TARGET_RESOURCE_ID" VARCHAR(191) NOT NULL,
	"TARGET_EXPRESSION" VARCHAR(191) NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DeviceMetricTable" (
	"ID" INT AUTO_INCREMENT,
	"CATEGORY" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ImmunizationRecommendationTable" (
	"ID" INT AUTO_INCREMENT,
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"TARGET_DISEASE" VARCHAR(2048),
	"VACCINE_TYPE" VARCHAR(2048),
	"IDENTIFIER" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "DocumentManifestTable" (
	"ID" INT AUTO_INCREMENT,
	"CREATED" DATE,
	"STATUS" VARCHAR(2048),
	"RELATED_ID" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"SOURCE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "ValueSetTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"CODE" VARCHAR(2048),
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"EXPANSION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"REFERENCE" VARCHAR(512),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "EvidenceVariableTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"EFFECTIVE" DATE,
	"TOPIC" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "RelatedPersonTable" (
	"ID" INT AUTO_INCREMENT,
	"ADDRESS_COUNTRY" VARCHAR(512),
	"ADDRESS_POSTALCODE" VARCHAR(512),
	"ACTIVE" VARCHAR(2048),
	"PHONE" VARCHAR(2048),
	"BIRTHDATE" DATE,
	"ADDRESS_CITY" VARCHAR(512),
	"EMAIL" VARCHAR(2048),
	"ADDRESS_STATE" VARCHAR(512),
	"TELECOM" VARCHAR(2048),
	"NAME" VARCHAR(512),
	"ADDRESS_USE" VARCHAR(2048),
	"ADDRESS" VARCHAR(512),
	"GENDER" VARCHAR(2048),
	"PHONETIC" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"RELATIONSHIP" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "TestReportTable" (
	"ID" INT AUTO_INCREMENT,
	"ISSUED" DATE,
	"PARTICIPANT" VARCHAR(512),
	"TESTER" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"RESULT" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "TestScriptTable" (
	"ID" INT AUTO_INCREMENT,
	"PUBLISHER" VARCHAR(512),
	"JURISDICTION" VARCHAR(2048),
	"CONTEXT" VARCHAR(2048),
	"URL" VARCHAR(512),
	"NAME" VARCHAR(512),
	"DATE" DATE,
	"STATUS" VARCHAR(2048),
	"DESCRIPTION" VARCHAR(512),
	"VERSION" VARCHAR(2048),
	"TESTSCRIPT_CAPABILITY" VARCHAR(512),
	"TITLE" VARCHAR(512),
	"IDENTIFIER" VARCHAR(2048),
	"CONTEXT_QUANTITY" VARCHAR(2048),
	"CONTEXT_TYPE" VARCHAR(2048),
	"VERSION_ID" INT NOT NULL,
	"CREATED_AT" DATETIME NOT NULL,
	"UPDATED_AT" DATETIME NOT NULL,
	"LAST_UPDATED" DATETIME NOT NULL,
	"RESOURCE_JSON" LONGBLOB NOT NULL,
	PRIMARY KEY("ID")
);


